# Generated by Django 3.0 on 2021-09-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
