# Generated by Django 3.1.7 on 2021-03-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ename',
            field=models.CharField(default='', max_length=50),
        ),
    ]
